cobolcheck.source.directory=src
cobolcheck.test.suite.directory=tests
cobolcheck.output.directory=testsuites
cobolcheck.cobol.program.compile.command=cobc -x
application.source.filename.suffix=cbl
test.suite.filename.suffix=cut
